[project]
name = "lookatni-docs"
version = "0.1.0"
description = "Documentation site for LookAtni File Markers"
requires-python = ">=3.8"

[tool.uv]
dev-dependencies = [
  "mkdocs-material>=9.5",
  "mkdocs>=1.6",
  "pillow",
  "cairosvg",
]

