site_name: LookAtni File Markers
site_url: https://kubex-ecosystem.github.io/lookatni-file-markers
repo_url: https://github.com/kubex-ecosystem/lookatni-file-markers
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kubex-ecosystem/lookatni-file-markers
  generator: false
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - Features:
    - Markers: features/markers.md
    - CLI: features/cli.md
    - VS Code Extension: features/extension.md
    - Tools: features/tools.md
  - Guide:
    - Configuration: guide/configuration.md
    - Workflows: guide/workflows.md
  - Community:
    - Contributing: community/contributing.md
    - Style Guide: community/style-guide.md
    - Roadmap: community/roadmap.md
  - Examples:
    - React Sharing: examples/react.md
    - Fixtures: examples/fixtures.md
