site_name: LookAtni File Markers Revolution
site_description: Advanced file organization system with unique markers for code sharing and project management
site_author: Rafa Mori
site_url: https://rafa-mori.github.io/lookatni-file-markers

repo_name: rafa-mori/lookatni-file-markers
repo_url: https://github.com/rafa-mori/lookatni-file-markers
edit_uri: edit/main/docs-site/docs/

theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  favicon: assets/icon.png
  logo: assets/icon.png

  icon:
    logo: logo

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rafa-mori
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/faelOmori
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rafa-mori/
    - icon: fontawesome/solid/globe
      link: https://rafa-mori.github.io

  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: rafa-mori
      repo: lookatni-file-markers
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Basic Concepts: getting-started/concepts.md
  - Features:
    - File Extraction: features/extraction.md
    - Marker Generation: features/generation.md
    - Validation System: features/validation.md
    - Visual Markers: features/visual-markers.md
    - CLI Tools: features/cli-tools.md
  - User Guide:
    - Commands Reference: guide/commands.md
    - Configuration: guide/configuration.md
    - Workflows: guide/workflows.md
    - Best Practices: guide/best-practices.md
  - Advanced:
    - TypeScript Scripts: advanced/typescript-scripts.md
    - Extension API: advanced/api.md
    - Architecture: advanced/architecture.md
    - Development: advanced/development.md
  - Examples:
    - React Project Sharing: examples/react-sharing.md
    - Backup & Restore: examples/backup-restore.md
    - CI/CD Integration: examples/cicd.md
    - Educational Use: examples/education.md
  - About:
    - Changelog: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
